name: deploy to production

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest

    steps:
      - name: check out code into the go module directory
        uses: actions/checkout@v3

      - name: load secrets and save to app.env
        run: |
          curl -1sLf \
          'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' \
          | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical
          export INFISICAL_TOKEN=${{ secrets.INFISICAL_TOKEN }}
          infisical export --env=prod > app.env

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: build and push docker image
        env:
          REGISTRY: ghcr.io
          GCR_REPOSITORY: gaggudeep/go-bank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$GCR_REPOSITORY:$IMAGE_TAG